---
version: '3'

services:
  master:
    build:
      dockerfile: master.Dockerfile
      context: .
    depends_on:
      - host
    volumes:
      - ./ansible:/ansible
  host:
    build:
      dockerfile: host.Dockerfile
      context: .
